### ISSUE TITLE
Reduce needed steps for JavaScript API test (semi auto or completely auto)

### ISSUE THREAD

**Issue by emanuelb** [ozguralp/gmapsapiscanner#7]
The script can do:
1. create html page with the API_KEY as received from command-line.
2. create local http server (http.server module / SimpleHTTPServer) and have the above HTML file return for /test endpoint.
3. visit the above page using headless-browser (if not implemented, tell the user to visit the created file on http://localhost:8090/test)
4. Detect the errors (use onerror event in HTML page) and show the status in the HTML file itself.

**Comment by ozguralp** [comment]
Thanks for useful comments, I am adding auto JavaScript API test checks to my to-do list for the script. Will update this issue once it is done.

**Comment by ozguralp** [comment]
On the latest update, I added a new feature which creates the file automatically for manually checking JS API. This would works for the efforts I think and checking with automatically within headless-browser would both need more installation requirements on user & development time with me. So I am closing the ticket since manual confirmation is easy within just opening the file on browser.

**Comment by bakliwalp** [comment]
@ozguralp As the tool creates automaticaaly a jsapi.html file, I opened it in the browser and it successfully loaded. So should I assume that the API key is vulnerable?? If yes, What will be the impact? can you please guide me?

**Comment by ozguralp** [comment]
> @ozguralp As the tool creates automaticaaly a jsapi.html file, I opened it in the browser and it successfully loaded. So should I assume that the API key is vulnerable?? If yes, What will be the impact? can you please guide me?

Well it is not well configured for the misuse attacks if it is successfully loaded and you can say it is vulnerable. About the impact, you can read my blog posts referred on the readme section.
